services:
  db:
    image: postgres:17
    container_name: postgres-ecom
    restart: 'no'
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: addidas1
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    container_name: redis-ecom
    restart: 'no'
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
